title: "Anonymous Submission"
description: "Supporting material for submission ZZZZ"
email: ""
baseurl: "" # leave blank for GitHub Pages root
url: "https://YOUR_GITHUB_USERNAME.github.io"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
markdown: kramdown

kramdown:
  math_engine: mathjax

# Include custom pages
include:
  - _pages

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Defaults for _pages
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      math: true # enables MathJax globally
      
